identifier_search:
    pattern:   /azonosito/kereses
    defaults: { _controller: AcmeRatingBundle:Identifier:search }

identifier_not_found:
    pattern:   /azonosito/nincs
    defaults: { _controller: AcmeRatingBundle:Identifier:notExists }

rateable_main:
    pattern:   /{alphanumericValue}
    defaults: { _controller: AcmeRatingBundle:Rateable:index }

rateable_by_id_main:
    pattern:   /id/{id}
    defaults: { _controller: AcmeRatingBundle:Rateable:indexById }

rateable_collection_main:
    pattern:   /hely/{alphanumericValue}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:index }

rateable_profile_by_id:
    pattern:   /profil/id/{id}
    defaults: { _controller: AcmeRatingBundle:Rateable:profile }

rateable_collection_public_profile_by_id:
    pattern:   /hely/profil/publikus/id/{id}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:publicProfile }

rateable_collection_profile_by_id:
    pattern:   /hely/profil/id/{id}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:profile }

rating_new:
    pattern:   /ertekeles/uj
    defaults: { _controller: AcmeRatingBundle:Rating:new }
