identifier_search:
    pattern:   /azonosito/kereses
    defaults: { _controller: AcmeRatingBundle:Identifier:search }

identifier_not_found:
    pattern:   /azonosito/nincs
    defaults: { _controller: AcmeRatingBundle:Identifier:notExists }

rateable_main:
    pattern:   /azonosito/{alphanumericValue}
    defaults: { _controller: AcmeRatingBundle:Rateable:index }

rateable_mismatch:
    pattern:   /azonosito/hibajelentes/{rateableId}
    defaults: { _controller: AcmeRatingBundle:Rateable:mismatch }

rateable_by_id_main:
    pattern:   /id/{id}
    defaults: { _controller: AcmeRatingBundle:Rateable:indexById }

rateable_upload_image:
    pattern:  /profil/kepfeltoltes/id/{id}
    defaults: { _controller: AcmeRatingBundle:Rateable:uploadImage }

rateable_collection_main:
    pattern:   /hely/azonosito/{alphanumericValue}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:index }

rateable_profile_by_id:
    pattern:   /profil/id/{id}
    defaults: { _controller: AcmeRatingBundle:Rateable:profile }

rateable_collection_public_profile_by_id:
    pattern:   /hely/profil/publikus/id/{id}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:publicProfile }

rateable_collection_profile_by_id:
    pattern:   /hely/profil/id/{id}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:profile }

rateable_collection_profile_edit_by_id:
    pattern:   /hely/profil/szerkesztes/id/{id}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:edit }

rateable_collection_upload_image:
    pattern:   /hely/profil/kepfeltoltes/id/{id}
    defaults: { _controller: AcmeRatingBundle:RateableCollection:uploadImage }

update_collection:
    pattern:   /hely/profil/szerkesztes/mentes
    defaults: { _controller: AcmeRatingBundle:RateableCollection:update }

new_rateable_for_collection:
    pattern:   /hely/profil/szerkesztes/uj/elem
    defaults: { _controller: AcmeRatingBundle:RateableCollection:newRateableForCollection }

update_rateable_for_collection:
    pattern:   /hely/profil/szerkesztes/uj/mentes
    defaults: { _controller: AcmeRatingBundle:RateableCollection:updateRateableForCollection }

rating_new:
    pattern:   /ertekeles/uj
    defaults: { _controller: AcmeRatingBundle:Rating:new }

contact_index:
    pattern:   /ugyfel/kontakt
    defaults: { _controller: AcmeRatingBundle:Contact:index }

update_contact:
    pattern:   /ugyfel/kontakt/mentes
    defaults: { _controller: AcmeRatingBundle:Contact:new }

contact_autocomplete_by_email:
    pattern:   /ugyfel/kontakt/email/autocomplete
    defaults: { _controller: AcmeRatingBundle:Contact:autocompleteByEmailPrefix }

client_autocomplete_by_client_id:
    pattern:   /ugyfel/kontakt/azonosito/autocomplete
    defaults: { _controller: AcmeRatingBundle:Contact:autocompleteByClientId }

vote_after_contact:
    pattern:   /ugyfel/kontakt/ertekeles/{token}/{stars}
    defaults: { _controller: AcmeRatingBundle:Contact:vote }
