parameters:
#    acme_rating.example.class: Acme\RatingBundle\Example

services:
#    acme_rating.example:
#        class: %acme_rating.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
