login:
    pattern:   /login
    defaults:  { _controller: AcmeUserBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

acme_rating:
    resource: "@AcmeRatingBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults:  { _controller: AcmeUserBundle:Default:loadWelcomePage }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
