acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AcmeUserBundle:Default:login }
login_check:
    pattern:   /login_check

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
