jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: AcmeUserBundle:User, property: username }
            
    firewalls:
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        homepage:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                #always_use_default_target_path: true
                #default_target_path: /
            logout: ~
        ajax_calls:
            pattern:    ^/_wdt
            anonymous:  ~

    access_control:
        - { path: ^/felhasznalo/profil, roles: 'ROLE_RATER' }
        - { path: ^/felhasznalo/regisztracio, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/felhasznalo/uj, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/felhasznalo/letezike, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/felhasznalo/jelszo, roles: 'ROLE_RATER' }
        - { path: ^/azonosito, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/id, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/profil/kepfeltoltes/id, roles: 'ROLE_MANAGER' }
        - { path: ^/hely/azonosito, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/profil/id, roles: 'ROLE_MANAGER' }
        - { path: ^/hely/profil/publikus/id, roles: '' }
        - { path: ^/hely/profil, roles: 'ROLE_MANAGER' }
        - { path: ^/ertekeles/uj, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/ertekeles/email/beallitas, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/ugyfel/kontakt/ertekeles, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/ugyfel/kontakt/hibajelzes, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/ugyfel/kontakt/azonosito/autocomplete, roles: 'ROLE_CUSTOMERSERVICE' }
        - { path: ^/ugyfel/kontakt/email/autocomplete, roles: 'ROLE_CUSTOMERSERVICE' }
        - { path: ^/ugyfel/kontakt/mentes, roles: 'ROLE_CUSTOMERSERVICE' }
        - { path: ^/ugyfel/kontakt, roles: 'ROLE_CUSTOMERSERVICE' }
        - { path: ^/jelentes/valaszto, roles: 'ROLE_MANAGER' }
        - { path: ^/jelentes/megtekintes, roles: 'ROLE_MANAGER' }
        - { path: ^/menedzser/nyito, roles: 'ROLE_MANAGER' }
        - { path: ^/quiz/questionnaire, roles: 'ROLE_MANAGER' }
        - { path: ^/quiz/upload, roles: 'ROLE_MANAGER' }
        - { path: ^/quiz/download, roles: 'ROLE_MANAGER' }
        - { path: ^/quiz/save, roles: 'ROLE_CUSTOMERSERVICE' }
        - { path: ^/quiz, roles: 'ROLE_CUSTOMERSERVICE' }
        - { path: ^/melysegi/kerdoiv/kovetkezo/kerdes, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/melysegi/kerdoiv/koszonjuk, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/melysegi/kerdoiv/uj/kerdes/urlap, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/uj/kerdes/alurlap/igennem, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/uj/kerdes/alurlap/skala, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/kerdes/valaszok, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/kerdes/letrehozas, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/kerdes/torles, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/sorrend/tipus/valtozas, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv/sorrend/valtozas, roles: 'ROLE_MANAGER' }
        - { path: ^/melysegi/kerdoiv, roles: 'ROLE_MANAGER' }
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }
        - { path: ^/$, roles: 'IS_AUTHENTICATED_ANONYMOUSLY,ROLE_RATER' }  
