jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: AcmeUserBundle:User, property: username }
            
    firewalls:
        admin_area:
            pattern:    ^/
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
