acme_user_load_welcome_page:
    pattern:  /
    defaults: { _controller: AcmeUserBundle:Default:loadWelcomePage }

acme_user_upload_image:
    pattern:  /felhasznalo/profil/kepfeltoltes
    defaults: { _controller: AcmeUserBundle:Default:uploadImage }

acme_user_data_update:
    pattern:  /felhasznalo/profil/mentes
    defaults: { _controller: AcmeUserBundle:Default:updateUserData }

acme_user_profile_edit:
    pattern:  /felhasznalo/profil/szerkesztes
    defaults: { _controller: AcmeUserBundle:Default:profileEdit }

acme_user_profile:
    pattern:  /felhasznalo/profil
    defaults: { _controller: AcmeUserBundle:Default:profile }

acme_user_registration:
    pattern:  /felhasznalo/regisztracio
    defaults: { _controller: AcmeUserBundle:Default:register }

acme_user_registration_done:
    pattern:  /felhasznalo/regisztracio/sikeres
    defaults: { _controller: AcmeUserBundle:Default:registrationDone }

acme_user_new:
    pattern:  /felhasznalo/uj
    defaults: { _controller: AcmeUserBundle:Default:new }

acme_user_does_exist:
    pattern:  /felhasznalo/letezike
    defaults: { _controller: AcmeUserBundle:Default:doesExist }

acme_user_password_change:
    pattern:  /felhasznalo/jelszo/modositas
    defaults: { _controller: AcmeUserBundle:Default:changePassword }

acme_user_password_update:
    pattern:  /felhasznalo/jelszo/mentes
    defaults: { _controller: AcmeUserBundle:Default:updatePassword }

acme_user_password_is_valid:
    pattern:  /felhasznalo/jelszo/ervenyese
    defaults: { _controller: AcmeUserBundle:Default:isPasswordValid }

