acme_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeUserBundle:Default:index }

acme_user_registration:
    pattern:  /user/register
    defaults: { _controller: AcmeUserBundle:Default:register }

acme_user_new:
    pattern:  /user/new
    defaults: { _controller: AcmeUserBundle:Default:new }
