acme_user_upload_image:
    pattern:  /felhasznalo/profil/kepfeltoltes
    defaults: { _controller: AcmeUserBundle:Default:uploadImage }

acme_user_profile:
    pattern:  /felhasznalo/profil
    defaults: { _controller: AcmeUserBundle:Default:profile }

acme_user_registration:
    pattern:  /felhasznalo/regisztracio
    defaults: { _controller: AcmeUserBundle:Default:register }

acme_user_new:
    pattern:  /felhasznalo/uj
    defaults: { _controller: AcmeUserBundle:Default:new }
