quiz_questionnaire:
    pattern:   /quiz/questionnaire/{rateableCollectionId}
    defaults: { _controller: AcmeQuizBundle:Default:questionnaire, rateableCollectionId: null }

quiz_upload:
    pattern:   /quiz/upload
    defaults: { _controller: AcmeQuizBundle:Default:upload }

quiz_download:
    pattern:   /quiz/download/{rateableCollectionId}
    defaults: { _controller: AcmeQuizBundle:Default:download }

quiz_main:
    pattern:   /quiz/{rateableId}
    defaults: { _controller: AcmeQuizBundle:Default:index }

quiz_save:
    pattern:   /quiz/save/{rateableId}
    defaults: { _controller: AcmeQuizBundle:Default:save }
